### ISSUE TITLE
note_entry.calc_left_of_primary_notehead has no body

### ISSUE THREAD

**Issue by Nick-Mazuk** [finale-lua/lua-scripts#153]
Currently, `note_entry.calc_left_of_primary_notehead(entry)` simply `return 0`.

https://github.com/finale-lua/lua-scripts/blob/0fb7ffcdc4183cc17dba075ca30f8b6887132ead/src/library/note_entry.lua#L177-L179

I suspect there was meant to be more in the body of the function.

**Comment by rpatters1** [comment]
It turns out that when an exp is set to left of primary notehead, the default position of the handle is exactly at that horizontal position, i.e., always zero. I left it in a function to encapsulate that and for completeness' sake. Makemusic could potentially introduce a future situation where it isn't zero.

**Comment by Nick-Mazuk** [comment]
Ah, I see. Thanks for the clarification!
