### ISSUE TITLE
[BUG] staff_rename.lua should use document preferences for font info

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#162]
The `staff_rename.lua` script should get the font info for Staff Name and Staff Abbreviated Name from the document preferences as follows:

```lua
    local full_font_info = finale.FCFontInfo()
    full_font_info:LoadFontPrefs(finale.FONTPREF_STAFFNAME)
```

```lua
    local abrv_font_info = finale.FCFontInfo()
    abrv_font_info:LoadFontPrefs(finale.FONTPREF_ABRVSTAFFNAME)
```

Similarly for multistaff instruments (i.e. `FCStaffGroup`) use `finale.FONTPREF_GROUPNAME` and `finale.FONTPREF_ABRVGROUPNAME` to get the fonts for group names.

I am tagging @jwink75 in hopes he'll do it as part of the changes for RGP Lua 0.62 (that will include autonumbering support). Or sooner, if you wish.

**Comment by jwink75** [comment]
Hey, just seeing this now... Don't know how I missed it earlier!

I was trying to preserve whatever font was already in place for the staff names... Although I'll admit it's pretty rare for someone to use something different. But as it is now if you want to do everything in Papyrus except the Trombones who you want in Comic Sans... It will totally accept that.

However, it doesn't handle situations with enigma tags in the middle of strings very well... I had a situation where I had some hidden text in the staff name and running this made it so the whole thing was hidden, since it extracts all the enigma tags it finds then puts them all in at the front of the new name.

But given that there are no really GREAT tools for resetting Staff Name fonts to the defaults... Yeah, I think this is a change I can happily make.

**Comment by jwink75** [comment]
Bwahahaha! Why not have the best of all worlds? I'm going to add a checkbox to use document fonts. It's not a bug... It's a feature!
