### ISSUE TITLE
[BUG] Output scripts still getting scrambled

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#264]
Just downloaded 3 different scripts from `finalelua/scripts` and they were all scrambled to the point of inoperability.

https://github.com/finale-lua/lua-scripts/blob/master/dist/layers_swap_selective.lua
https://github.com/finale-lua/lua-scripts/blob/master/dist/transpose_by_step.lua
https://github.com/finale-lua/lua-scripts/blob/master/dist/transpose_enharmonic_up.lua

In common: they all require library files.

**Comment by Nick-Mazuk** [comment]
cc @ThistleSifter 

It seems like these scripts are trying to `require("mixin.FCMResourceWindow")` for some reason. This module does not exist in the codebase. Furthermore, I cannot find any reference to this anywhere in the codebase, not even the word "resource" (outside of our docs).

Still exploring to see why this is happening in the bundled versions but not the original version.

**Comment by Nick-Mazuk** [comment]
From my testing so far, this seems to be isolated to mixins. Several other scripts I've tried that don't use mixins still work as espected (e.g., `layers_swap_1_2.lua`).

**Comment by cv-on-hub** [comment]
> this seems to be isolated to mixins

That seems to be true.

**Comment by Nick-Mazuk** [comment]
@ThistleSifter 

When writing the mixin code, were you depending on a specific behavior of the `require` function?

That function is overwritten when bundling the scripts. The more I dig into this, that seems to be the root cause. With that said, I still have no idea why `mixin.FCMResourceWindow` is being required.

**Comment by Nick-Mazuk** [comment]
Ok, making some progress. For some reason, it thinks that `FCMCustomWindow` inherits from `FCMResourceWindow`.

Adding this debug statement…

```lua
print("Mixin '" .. class_name .. "' inherits from '" .. class.props.MixinParent .. "'")
```

…above this line…

https://github.com/finale-lua/lua-scripts/blob/1b5e1124fcf546912f7e69919278c50bcebec99d/dist/transpose_by_step.lua#L7732


…yields this output.

```
Mixin 'FCMCustomWindow' inherits from 'FCMResourceWindow'
```

Here's the equivalent line of code in the original.

https://github.com/finale-lua/lua-scripts/blob/1b5e1124fcf546912f7e69919278c50bcebec99d/src/library/mixin.lua#L370

---

This behavior seems to be identical to unbundled version. Just that for some reason in the unbundled version `FCMResourceWindow` seems to exist and inherits from `_FCMUserWindow`?

@ThistleSifter Where is `FCMResourceWindow` defined? I cannot find any reference to it in the repo!

**Comment by Nick-Mazuk** [comment]
After a bit more digging, I believe here is the root cause of the issue. This is the custom function in `library.mixin` that requires the mixins.

https://github.com/finale-lua/lua-scripts/blob/1b5e1124fcf546912f7e69919278c50bcebec99d/src/library/mixin.lua#L305-L314

`pcall` here is meant to run the require function, then catch any errors.

https://github.com/finale-lua/lua-scripts/blob/1b5e1124fcf546912f7e69919278c50bcebec99d/src/library/mixin.lua#L309

Then this line checks to see what kind of error occurred. If it was not the expected kind (i.e., "module not found"), then it propagated the error. However, if the module was actually not found, then it would continue like normal.

Now this is a problem because of the new `require` function. If the new `require` function fails, it doesn't throw a "module not found" error because it isn't loading modules. Instead, it throws a "this item cannot be called because it's nil" error.

https://github.com/finale-lua/lua-scripts/blob/1b5e1124fcf546912f7e69919278c50bcebec99d/dist/transpose_by_step.lua#L3-L5

Simply updating the function to throw the expected kind of error if the import doesn't exist seems to fix this issue locally. PR coming soon.

```lua
function require(item)
    if __imports[item] then
        return __imports[item]()
    else
        error("module '" .. item .. "' not found")
    end
end
```

---

Apologies for the email spam. I've been having trouble focusing today and was not sure if I'd be able to finish debugging this or not. So I kept my notes here so someone else could jump in if needed.

**Comment by ThistleSifter** [comment]
Sorry I couldn't reply, I was away from the computer.

You pretty much worked it out. Basically, for `FCM` mixins, it finds the corresponding standard `finale` object, goes through each level of the inheritance tree and checks if there is an `FCM` mixin for that class. If there is, it loads it. If not, it marks it as checked and won't check again (internally it just substitutes an empty mixin). Then it goes onto the next parent, etc, etc, until reaching `__FCBase`. That way, a registry of mixins doesn't need to be kept; the files are all that's needed.
