### ISSUE TITLE
Naming scripts

### ISSUE THREAD

**Issue by Nick-Mazuk** [finale-lua/lua-scripts#270]
> There’s not necessarily a conventional naming system for the scripts, so categories of things like Layers for example - You’ve got "Layers Hide" and "Layers Mute", which will end up next to each other alphabetically in the menu, but "Swap Layers" will end up way farther down.  But I can rename the last one "Layers Swap” and that will put that script next to the other Layers scripts in the menu.  Anyway, this is just my thought process here.  I’m trying to figure out the best organization for these.  Because… I suppose there is going to be an ever growing list of these and even just keeping track of them is gonna be a challenge at some point!

This is from an email I received from Jason Loffredo.

At some point we should probably figure out a standard for naming scripts. It seems like each of us has our own system, but they are not necessarily the same between each of us.

cc @rpatters1 @cv-on-hub @jwink75

**Comment by rpatters1** [comment]
The Category string in `plugindef` seems to be how Jari was planning to organize this issue. (If the JW Lua plugin itself does anything with it, I haven't figured it out.)

Rather than trying to standardize file names (which will always be a tussle), I would recommend expanding or modifying the Category strings to an extend list (more than Jari's original list) and using those to present them to users on the website.

**Comment by cv-on-hub** [comment]
I've tried to standardise at least my own script names, with a primary-affected-item-first convention that I thought I saw hinted at somewhere in the Hub documentation. **Category string** would certainly be the most sensible use of `plugindef`, though I keep forgetting to include the categories.

**Comment by jwink75** [comment]
This is something that I think has evolved somewhat over time. For example, I would bet that 'Swap Layers' was mine initially, but if I were submitting it today I would 100% have named it layer_swap_1_2 or something for just that reason. I try to stick with the idea of going big to small... What does the script affect at the highest level, then getting more specific from there.

Perhaps a tidying pass is in order, and that's also something we should all pay close attention to in the future as well!

On 7/27/2022 2:13:34 PM, Nick Mazuk ***@***.***> wrote:
There’s not necessarily a conventional naming system for the scripts, so categories of things like Layers for example - You’ve got "Layers Hide" and "Layers Mute", which will end up next to each other alphabetically in the menu, but "Swap Layers" will end up way farther down.  But I can rename the last one "Layers Swap” and that will put that script next to the other Layers scripts in the menu.  Anyway, this is just my thought process here.  I’m trying to figure out the best organization for these.  Because… I suppose there is going to be an ever growing list of these and even just keeping track of them is gonna be a challenge at some point!
This is from an email I received from Jason Loffredo.
At some point we should probably figure out a standard for naming scripts. It seems like each of us has our own system, but they are not necessarily the same between each of us.
cc @rpatters1 [https://github.com/rpatters1] @cv-on-hub [https://github.com/cv-on-hub] @jwink75 [https://github.com/jwink75]
