### ISSUE TITLE
RFC: Image Controls in RGP Lua

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#327]
# Potential Image Control in RGP Lua

### The Problem
Several of you have requested an image control that could be placed on `FCCustomWindow` dialog boxes. Adding the control itself may not be that difficult, but what becomes trickier is where the images come from. Normal applications use resources (that optionally can be different by locale) and place them in `.bundle` files (actually hidden folders in macOS) or embed them directly in `.exe/.dll` files (Windows). Lua scripts have neither of those options.

### Possible Solutions
Based on preliminary research into creating image controls on both platforms, it appears that it may be possible to do either or both of the following:

- Accept images from files (`.bmp` on Windows and a bunch of standard formats on Mac presumably including `.bmp`.)
- Accept images from data buffers.

### More Detailed Design Considerations

In addition to a putative `FCCtrlStaticImage` control, RGP Lua will need to add something like an `FCImage` class. I imagine this class either being initialized from a memory buffer or a filepath and then attached to the control. This process could be embedded in the control so that scripts did not have to do it themselves, but I would want them to be able to access the `FCImage` if they needed to. It would be loosely based on Apple's [NSImage](https://developer.apple.com/documentation/appkit/nsimage?language=objc) class (with far fewer options).

The question arises as to where to put image files that the script needs. As external dependencies they would create a headache for deployment and support, unless you were creating a completely self-contained "app" with an embedded copy of RGP Lua. But in the general case, external files are messy.

Another option would be to use a tool like `xxd` (macOS/Unix only, though I believe there are 3rd-party Windows versions). You could dump the image file as a `.png/.bmp` (i.e., pure RGB Data) and then embed it as a table of characters in your script that could be passed to the control. It would also be straighforward to create our own version of `xxd` to output the files in a more Lua-friendly format. Something like

```lua
local my_cool_image = [[
\x23x\3x\0x\234\23 ...
]]
```

Jan Angermüller actually attaches a binary chunk of data to the end of one of his script files that he then reads from his own script file. (That's what the `finaleplugin.LoadAsString` option is for. RGP Lua loads the entire file but then passes it as a string to Lua. Because the separator of the script from the binary data is a null character, Lua stops processing the file when it encounters the null.) Images could be attached that way.

### Additional Considerations.
So far this discussion is centered on static images. For those of you who have been asking for this, do static images address what you need? I have not investigated animated images.

cc: @Nick-Mazuk @jwink75 @CJGarciaMusic @CJGarciaMusic @ThistleSifter

**Comment by Nick-Mazuk** [comment]
I haven't personally needed images, but this should work. Few questions, though:

1. Would this support dark mode? I'd prefer to not have a repeat of Finale's "artistic" renditions of dark mode images if possible.

<img width="636" alt="Screen Shot 2022-08-09 at 9 13 20 PM" src="https://user-images.githubusercontent.com/5659171/183813702-2864d902-7e67-4aef-ba53-c2fcef183dfa.png">

2. Would it be possible (or wise) to fetch images via a URL instead of storing it inside the script? If this were implemented, I think fetching via a URL should be an alternative of storing the actual bytes, not a replacement for the proposed API. I'm fine if this is never implemented. Just curious what the possibilities are.


3. Specific to this repo, my ideal developer experience would be one where developers can store the images directly in this repo as PNGs or Bitmaps, then have some sort of library function that can import the file from the outside file. Finally, when bundling it, the image data is inlined into the Lua file. That way, as we're doing code review or updating each other's scripts, we can see the image directly rather than a big blob of nonsense text (GitHub shows visual diffs for image changes, too). Additionally, then we won't have that big blob of nonsense text in the source files as we code. If possible, I'd like to find a way to support this use case. Luckily, it seems like the proposed API would allow this.

```
local image = require("library.image")
local image_a = image.import("image_a.png")
```

**Comment by JAngermueller** [comment]
Thanks a lot, Robert, for having a look at this!

I use images in Perfect Layout for showing the effects of options ("Before"/"After").

Currently there is a tiny button next to the option which opens up a preview image from a URL in the standard web browser.
Not very comfortable for the user, but at least he already sees a preview.

The images are currently not standardized and some are pretty huge, so they won't fit into the standard dialog anyway.

Here are a few examples:
https://elbsound.studio/assets/img/ES/hairpinconnection.png
https://elbsound.studio/assets/img/ES/dynamics%20shifted%20up.jpg
https://elbsound.studio/assets/img/ES/preventbarlinecollisiondynamicsabovethestaff.jpg
https://elbsound.studio/assets/img/ES/hidegroupnamesinparts.jpg

If the images were somehow available directly to the plug-in, I would probably keep the same method and only open a new dialog window with the preview images instead of the web browser. 
This is (slightly) more comfortable as it keeps the focus on RGP Lua.

In the longterm I might add more sub dialogs and reduce the images to give the user a better experience by showing a preview directly next to an option.
But this would mean a lot of redesign on the user interface with about 300 options and is currently not my top priority.

My problem is that Perfect Layout already includes more than 100 preview images, so encoding them in the \x23,... format based on .bmp that Robert suggests would yield in quite some overhead compared to compressed .jpg/.png.
However, if the plug-in only needs 2-3 images (as probably most plug-ins) this might be a good "offline solution".

Looking at one average example image to calculate the size for 100 images:
.jpg image:  42 KB
.bmp image: 110 KB
Size if one byte is encoded as 4-5 bytes (255=\xFF,): ca. 550 KB
100 images x 550 KB= 55000 KB = ca. 54 MB

Downloading the images from a URL ("Online solution") would be my alternative suggestion which brings up the issue of "Downloading Files" in RGP Lua. BTW I had been talking about this with Robert yesterday (I'll add another issue for this one...).

Reading the images on the fly during runtime from a given file name would be my second preferred solution - especially as in Perfect Layout the images are only shown "on demand" when the user clicks a preview image button.
My plug-ins also use other external files and an installer, so there is always a known folder structure where the images are available and I don't see a problem in loading these images.

Appending binary code at the end of the plug-in is possible, but requires scrips for attaching and for reading/decoding. 
I think it's also only possible if the Lua script is already compiled (but I am not sure). At least the Perfect Layout script is first compiled and then the binary code is attached.
That's probably a too complex way for a simple plug-in with only one image.

Animated images are interesting: 
it could save space in the dialog if you have a before/after image that only requires the space for one image (and not two).
But instead of supporting an animated format like .gif, maybe it's possible to simply show/hide two .bmp images at the same spot alternatively in a certain time interval. 

My general suggestion/requirements would be:
-Add an image class that takes the binary code of an image as source (i.e. from a lua variable). Then downloading, reading files, decoding text arrays or reading attached binary code is possible and it's up to the developer how he puts the image into the variable.
-If possible, support multiple formats like .bmp, .png, .jpg. If too difficult (or as a first quick solution) only support .bmp or .png.
-Having more than 100 images of which maybe not even a single image is actually shown (if the user doesn't click a preview button) shouldn't slow down the startup performance of the plug-in significantly. Or in other words: if possible, the images should only be loaded just-in-time if a dialog needs them.
-If this works, then a second step could be a more developer-friendly interface which also accepts file names, URLs or .lua files (with Robert's encoded text arrays as described above) as input

**Comment by rpatters1** [comment]
- I have no idea how to do animated images, so (just to be clear), I'm not offering them (at least not yet).
- Same goes for Dark Mode. I haven't even begun to investigate if I can get this control to work, so until that happens I prefer to punt on worrying about Dark Mode. At a minimum I'm hoping that images with transparent backgrounds will be easy.
- Loading images from a URL is not a bad idea, though it means the website has to be available in perpetuity for the script to work properly. (I don't think requiring a website is a great idea. Websites vanish all the time. I heard even Google search was down for a while over the weekend.)
- macOS would allow you to bundle the whole thing in a folder that looks like an individual file. But on Windows it would still look like a folder.
- images could be loaded as needed, even if in a text array, using the `require` statement. However that basically defeats the purpose of having them in a text array. My goal would be to support all common formats through a file loading API. This appears to be built in to macOS Cocoa, and I have to think there is a good open-source solution for Windows. If someone wants to suggest one, I'm listening. What's needed is a library that reads the file into an `HBITMAP` handle.

**Comment by rpatters1** [comment]
I have uploaded a prerelease version of 0.64 that contains `FCCtrlImage`. This control allows you to load images from a file, a url, or a Lua string that is a direct binary image of one of the supported file types. I've tested both Mac and Win versions with `.jpeg`, `.giff`, `.ico`. I expect it also works with `.bmp`, `.png`, and others as well, but I haven't (yet) tried them. In fact that's where I'm hoping for help.

In addition this version has numerous other improvements over the previous pre-release version including `FCUI::GetUserLocaleName` and `FCCtrlRadioButtonGroup`.

You can download it [here](https://drive.google.com/file/d/1unREn14SaQVgBKVndxOIsoqf-nryAEHv/view?usp=sharing).

You can get the latest PDK Framework docs that match this version on the [master branch](https://github.com/finale-lua/pdk-framework-docs) of the repository. I've added a fair amount of documentation of `FCCtrlImage` there.

I added a `create_string_buffer_from_file.lua` script to the creation tools in [lua-testtoolkit](https://github.com/finale-lua/lua-testtoolkit). You can use this to create Lua strings that can be loaded into the image control.

This is a good time to offer feedback if you have it.

**Comment by rpatters1** [comment]
Just to let everyone know, I am going to remove the `SetImageFromUrl` api. This is because it is extremely dis-recommended to download file across the Internet in a synchronous routine. You can end up blocking all user interaction to the app. It is quite possible I could get pushback from MakeMusic against merging it into the PDK Framework repo.

As an alternative, I will be investigating how to include the full suite of `luasocket` tools into the Finale Lua environment. You'll be able to use the `socket.http` namespace to create asynchronous web call, perhaps using a Lua `coroutine`. (I have used a coroutine before and it is really easy and works quite well.)

**Comment by rpatters1** [comment]
Also, I will be adding a FCUI::IsDarkMode method that will allow you to select a different image if you are in Dark Mode.

**Comment by rpatters1** [comment]
This has been implemented for the next release of RGP Lua, including many of the ideas in this thread. I'm closing this issue. If someone wants to reopen it, feel free.

**Comment by jwink75** [comment]
Even loading a single static image would be amazing in certain cases, I think. Even better would be multiple images - at that point maybe we could even programmatically add our own crude animations :) But seriously, even one would be great.

One interesting thing to check out might be how images interact with other elements. I know in messing about with my scripts with dialog boxes that Windows and Mac handle drawing the controls very differently. In addition to the differences between size, I’ve noticed that if I’m not proactive about , say, the width of checkboxes they get drawn in such a way that many of them get obscured and ‘covered’ up by the width of other elements and end up not getting drawn. It’s easy for the Windows dialogs to turn into an ugly mess. Since one potential use of a graphic might be adding a ’skin’ to a dialog, the Windows drawing issues are a potential concern.

But we’ve got to start somewhere, so I say again that just being able to add a single graphic would be amazing!

-Jake

**Comment by rpatters1** [comment]
> But we’ve got to start somewhere, so I say again that just being able to add a single graphic would be amazing!

It's there in RGP Lua 0.64. (the current release)
