### ISSUE TITLE
CSV support in Configuration

### ISSUE THREAD

**Issue by jwink75** [finale-lua/lua-scripts#341]
Hey folks,

I adapted the configuration functions to read a CSV not too long ago because I had long list of search/replace terms, and it worked like a charm. I'm thinking that might make a useful library addition. In fact, I was thinking it might be a useful way of adding a table array: The first column could be the key, if there is only one other cell in the row it would be the value, but if there are multiple entires in after the first column they would be a table.

Right now I think mostly being able to read would be what I'm interested in... haven't tried writing a CSV with Lua.

The question I have is: Should I try to adapt the existing function(s) to also accommodate CSV files, or should I add new CSV variations of functions like get_parameters_from_file()?

**Comment by jwink75** [comment]
If the CSV file was:

R1C1, R1C2
R2C1, R2C2, R2C3
R3C1, R3C2, R3C3, R3C4

Then the "load from CSV" file would yield:
{["R1C1"] = R1C2, ["R2C1"] = {R2C2, R2C3}, ["R3C1"] = {R3C2, R3C3, R3C4}}

**Comment by ThistleSifter** [comment]
My understanding of CSVs is that they're degned for tabular data, where you have a set of column headings and then every row contains fields for each column. This usage of a CSV is almost like rotating the table 90° to the left, with "headings" down the left hand side.

I haven't had any real-world experience with using CSVs (other than reading about them and playing with MySQL exports) so I don't know if this kind of alternative usage is common or accepted. If it is, then disregard this, otherwise I'd probably suggest picking a more suitable format which is designed to hold these different data types (eg JSON).

Another option could be to expand the current code to allow multi-dimensional tables.

**Comment by rpatters1** [comment]
The config library already allows tables:

```
table_name = {12, "dsfsf", true, 17}
```
I refer you to the documentation:

>Parameter values may be:
>
>- Strings delimited with either single- or double-quotes
>- **Tables delimited with `{}` that may contain strings, booleans, or numbers**
>- Booleans (`true` or `false`)
>- Numbers
>
>Currently the following are not supported:
>
>- Tables embedded within tables
>- Tables containing strings that contain commas

(emphasis added)

The main reason for the two limitations is how it detects commas. This could be easily rectified, but so far that has been no requirement forit. If you still must have CSV support, please add it in a new function rather than incorporating it into any existing ones.

**Comment by rpatters1** [comment]
I would also encourage us to consider using an existing Lua CSV library rather than inventing one to this repo. [Lua-CSV](https://github.com/geoffleyland/lua-csv) looks interesting.

**Comment by jwink75** [comment]
Robert, what would be the accepted method for integrating an existing Lua library into repo scripts? Would I just upload it wholesale to our repo so that any "require" statements still work? I was thinking that having our own would keep the naming conventions consistent.

Also, I want to emphasize that I don't currently have any real use for this other than the instance I mentioned earlier, where I had a long list of terms that I wanted to search/replace on and Excel was clearly the right tool for the job... I can certainly drop it (at least until the next time I feel like I need it!).

**Comment by jwink75** [comment]
ThistleSifter: I think that last point is the reason I was looking for CSV rather than something else like JSON. While there are ways to convince Excel to output JSON-ish files, exporting as CSV has been an option forever. Since Lua still processes CSV files left to right, line-by-line, I still think organizing data by rows makes the most sense for processing.

**Comment by rpatters1** [comment]
I don't think a one-off CSV function belongs in this repo at all. It has nothing to do with Finale, and it an already-solved problem. I would urge you to look into using [Lua-CSV](https://github.com/geoffleyland/lua-csv) instead for your own code. It appears to be lightweight, pure Lua, and easy to use. We could discuss including it as a submodule here, or just a plain old copy (like I did with the json library).

**Comment by jwink75** [comment]
Not to be too argumentative, but if the CSV is providing data in order to manipulate a Finale file, then it has _everything_ to do with Finale, not nothing as you suggest :) I don't need to belabor this, though: I've only encountered the one circumstance where I felt I needed something like this, so you're probably right that it is of limited use as a general library.

**Comment by rpatters1** [comment]
Have you looked at Lua-CSV? In your shoes I would consider converting to it.

Reading a CSV per se has nothing to do with Finale, *and* it's already solved. The second part is important too. What your program does with the data after is another matter.
