### ISSUE TITLE
[HELP] Preferences objects

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#428]
I'm working on a plugin that will read all current document preferences and write them out to a YAML file, along the same lines as Robert's "Save Document as Text File".

1. These three prefs objects throw an error when I call their constructor: `FCHumanPlaybackPrefs`, `FCPartExtractPrefs`, `FCSlurContourPrefs`. The error is "Attempt to call 'FCHumanPlaybackPrefs' (a nil value)". For slur contour, the bit in parens says "a table value". I can see in the docs that human playback doesn't have a public constructor, part extraction doesn't say it's Lua supported (but also doesn't say that it's not), and slur contour is explicitly not Lua supported. I don't know what's involved in making something Lua supported -- is there a reason these three are not, or is it possible to add that? **Edit:** I found the way to load slur contour prefs via smart shape prefs.
2. During the call to `dumpproperties()`, `FCGeneralPrefs` throws an error: "GetQuantizationUseSensitivityLevel requires a minimum Finale version of Finale 27.3". As a result, I'm not able to access any of the properties on that object. Is it possible for `dumpproperties()` to be smarter, so that it doesn't try to dump properties it can't access under the current Finale version (I'm running 25)? 
3. `FCTieContourPrefs` and `FCTiePlacementPrefs` follow a different pattern than other similar classes. Instead of passing a constant into `Load()` to determine which set of prefs to load (e.g., short, medium, long, tie ends for tie contour), the constant needs to be passed to each getter, which means that `dumpproperties()` returns an empty table. I can work around this by coding property retrieval by hand for each class, but is there a reason that these two are like this?

**Comment by asherber** [comment]
Update: Since I'm focusing on preferences that affect engraving, I no longer need `FCHumanPlaybackPrefs` or `FCPartExtractPrefs` from point 1, or `FCGeneralPrefs` from point 2, and I've worked around the issues in point 3.

So nothing here is a blocker, but I'm still interested in the answers!

**Comment by rpatters1** [comment]
- `FCHumanPlaybackPrefs` is not available in Lua. (In fact, it is barely implemented even in C++. It looks more like a stub that Jari might have thought he would get to at a future date.)
- `FCPartExtractPrefs` is not available in Lua. According the comment in the docs, it appears to be obsolete post F2007.
- You could create your own version of `dumpproperties` to do whatever you need it to do. The source code is [here](https://github.com/finale-lua/lua-source/blob/master/built-in-functions/rgplua_built_in_functions.lua). If you think a change is needed in the built-in version, post a PR there. Any merges will be included in the next version of RGP Lua.
- Due to a major change in how prefs work starting in F26.2, it is now necessary to access the placement and contour prefs of ties through a `FCTiePrefs` instance. This approach should also work in F25.

**Comment by asherber** [comment]
Thanks, Robert! Are there any release notes anywhere for RGPLua and the PDK Framework? 

And for the Framework doc pages, is it possible to reformat things so that the Detailed Description appears higher up on the page, maybe even right under the inheritance diagram? There's a lot of useful info down there, and it would be nice if it were more visible.

**Comment by rpatters1** [comment]
Version history is on my website [here](https://robertgpatterson.com/-fininfo/-rgplua/vershist.html).

The Framework doc pages are generated by Doxygen, and I don't know how configurable they are, if at all. I would be happy to make a change if you know of a change that can be made. In the mean time, there is a short blurb about each class at the top of its page, with an easy link to the full description. It has never seemed to me like it was that difficult to find out about them.

**Comment by asherber** [comment]
From the perspective of someone who's new to this framework, it didn't occur to me that I'd need to click or scroll that far down the page to find out that usage of a class has changed. But now that I know....
