### ISSUE TITLE
dialog:CreateTextEditor() steals keyboard focus

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#681]
Kicking the tyres on `utils.show_notes_dialog()` I've noticed that when the dialog opens (on Mac) [Return] and [Enter] only activate "OK" on the second click. If a "Cancel" button is provided then [Escape] works on the first click like it should. Setting `ok:SetKeyboardFocus()` in `RegisterInitWindow()` doesn't help.

This seems entirely due to `dialog:CreateTextEditor()`, regardless of its finer settings.  Simple static text doesn't steal the first [Enter] click like that.

Simple sample script attached.
[test.lua.txt](https://github.com/finale-lua/lua-scripts/files/14173585/test.lua.txt)

The other problem with `utils.show_notes_dialog()` is that it steals document focus, which seems true of all secondary dialogs launched from a "primary" (modal) dialog, which is the most likely use situation for `show_notes_dialog()`. The second dialog call must be followed by `finenv.UI():ActivateDocumentWindow` to return focus to the active document. Is that how it __should__ work?

**Comment by rpatters1** [comment]
Any modal dialog opened from a modeless dialog should be passing the modeless dialog to `ExecuteModal`. So `show_notes_dialog` should almost certainly be enhanced to include an (optional) `parent` argument that is passed to `ExecuteModal`.

That probably doesn't help this issue on macOS. (It mainly addresses a different Windows issue.) I'm not sure what you expect it to do. If you are clicking a button on the modeless dialog to launch the info window, that click is what is taking the focus away from the document window. That seems like the correct behavior to me. There is no way for the utility function to know if the modeless parent was in focus before the click or if the document window was in focus before the click. If you want focus to go back to the document, you should probably implement that yourself, but I don't recommend it.

Modeless plugin dialogs on MacFin have a long and troubled history with document focus (since the transition to OSX), but some years ago I figured out how (mostly) to mitigate it. I have never been able to convince MakeMusic to adopt my solution, however. If you want to fully experience the awfulness of it, try using any of the built-in modeless plugins without my Patterson plugins installed. (Or with my 3rd-party focus option disabled.) Then leave one of them open and try to use Speedy or open any modal dialog. It truly was the slag mines.

**Comment by rpatters1** [comment]
The other issue with the return key looks like an RGP Lua bug to me. I'll see if there is anything I can do about it.

**Comment by cv-on-hub** [comment]
> Any modal dialog opened from a modeless dialog should be passing the modeless dialog to `ExecuteModal`. 

Also seems to be true for opening a modal dialog from a modal dialog. Is that true? This has bugged me for ages, and I didn't pay enough attention to a fleeting reference you made somewhere some time back. My [hotkey_script_palettes.lua](https://raw.githubusercontent.com/finale-lua/lua-scripts/master/src/hotkey_script_palettes.lua) has had this problem since day zero. Now seemingly fixed with `ExecuteModal(parent_window)`.

The return key thing was baffling until I made duplicate dialogs with, and without, an `FCCtrlTextEditor`.

**Comment by rpatters1** [comment]
Yes it is also true for opening a modal from a modal. But it matters most on Windows. On Mac it just determines the default position where the new dialog opens. On Windows, it affects the modalness. If you pass `nil` (on Windows) the new dialog is only modal to the Finale main window. You can still access the window that launched it.

**Comment by rpatters1** [comment]
I should add: it is for this reason I added the `CreateChildUI` to `__FCUserWindow`. That allows alerts and standard file open/save dialogs to be modal to the window that launches them, too.

**Comment by rpatters1** [comment]
I have implemented a fix in RGP Lua for v0.71. Calling `ok:SetKeyboardFocus` will now have the desired effect on macOS as well as Windows.

**Comment by cv-on-hub** [comment]
> On Mac it just determines the default position where the new dialog opens.

On exit, a Modal dialog that has invoked a child modal dialog on MacOS (even supplied with a suitable `parent`) seems to return focus to the `Playback Controls` window if it's present, not the active Document.  Alluding to the _slag mines_ you mention. Unless I'm missing something, `ActivateDocumentWindow` might still be necessary. (You can check this in simplest example with the `test` script I attached above).

**Comment by rpatters1** [comment]
This is a rabbit hole I advise you not go down.

**Comment by cv-on-hub** [comment]
Are there times when `finenv.UI():ActivateDocumentWindow` should be used?

**Comment by cv-on-hub** [comment]
I think this issue has been confronted and discussed sufficiently in various other threads and PR's to be considered __closed__.

**Comment by rpatters1** [comment]
RGP Lua 0.72 will address this issue.

**Comment by rpatters1** [comment]
Actually, I take it back. That change made it into 0.71, so it's fixed.
